hyperparameters: 
    nTemporal    : 1
    nReservoir   : 1000
    alpha        : 0.81
    rho          : 0.998
    gamma        : 0.005 # fixed
    phi          : 0.50  # fixed
    sparsity     : 0.90
    percentile   : 0.95
    randomSeed   : 18
    hiddenSize   : 64

experimentParameters:
    learningRate : 0.001
    learningRateT: 10
    nEpoch       : 20
    nCheck       : 5
    nOperation   : None
    optimizer    : Adam

modelParameters:    
    readoutType  : 'nRes'
    thetaLearning: False
    FNA          : False
    nInput       : 360
    nOutput      : 2
    thetaInitAll : False  # Blending all three datasets for theta init
    
experimentDetails:
    dataset      : 'AntWorld++02'
    problem      : 'BPR'
    model        : 'ESN_NA' 
    labelFreq    : 100
    nImages      : 1000
    tolerance    : 1
